name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  testing-env:
    runs-on: windows-latest
    timeout-minutes: 3

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: .env variables
        run: |
          type nul > .env
          echo GOOGLE_KEY=${{ secrets.GOOGLE_KEY }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env

      - name: Run tests
        run: npm test

  format-code:
    if: success()
    needs: [testing-env]
    runs-on: windows-latest
    timeout-minutes: 3
    permissions: 
      contents: write

    strategy:
      fail-fast: false
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3
     
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set up Git
        run: | 
          git config user.email "github_action@github.com"
          git config user.name "github robot"
      
      - name: Format code and push changes
        env: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run format
          git commit --allow-empty --all -m "[Automated commit] - formatted Code"
          git push
